# Generated by Django 4.1.5 on 2023-06-29 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_app', '0003_mpesacallsnew_delete_mpesacalls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MpesaCallsNew',
        ),
    ]
